name: untitled5
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
dependencies:
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.3
  firebase_core: ^2.24.2
  provider: ^6.1.1
  flutter:
    sdk: flutter



  shared_preferences: ^2.2.2
  cupertino_icons: ^1.0.6
  http: any


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
    - assets/images/bio.png
    - assets/images/goal.png
    - assets/images/logo.png
    - assets/images/order_food.jpg
    - assets/images/veggies.png
    - assets/images/welcome.jpeg

